language: cpp
before_install: ./util/travis/before_install.sh
script: ./util/travis/script.sh
sudo: required
dist: trusty
group: edge
notifications:
  email: false
matrix:
  fast_finish: true
  include:

    - env: CLANG_FORMAT=clang-format-7
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-format-7']
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - name: "Builtin Luacheck and Unit Tests"
      language: generic
      compiler: null
      os: linux
      sudo: false
      addons:
        apt:
          packages:
          - luarocks
      before_install:
        - luarocks install --local luacheck
        - luarocks install --local busted
      script:
        - $HOME/.luarocks/bin/luacheck builtin
        - $HOME/.luarocks/bin/busted builtin

    - env: CLANG_TIDY=clang-tidy-7
      compiler: clang
      os: linux
      script: ./util/travis/clangtidy.sh
      addons:
        apt:
          packages: ['clang-7', 'clang++-7', 'clang-tools-7', 'clang-tidy-7']
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: PLATFORM=Win32
      compiler: gcc
      os: linux

    - env: PLATFORM=Win64
      compiler: gcc
      os: linux

#    - env: PLATFORM=Unix
#      compiler: clang
#      os: osx
#      osx_image: xcode8

    - env: PLATFORM=Unix COMPILER=gcc-6
      compiler: gcc
      os: linux
      addons:
        apt:
          packages: ['gcc-6', 'g++-6']
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: PLATFORM=Unix COMPILER=gcc-8
      compiler: gcc
      os: linux
      addons:
        apt:
          packages: ['gcc-8', 'g++-8']
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: PLATFORM=Unix COMPILER=clang-3.6
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-3.6', 'clang++-3.6']
          sources: &sources
            - llvm-toolchain-trusty-3.6

    - env: PLATFORM=Unix COMPILER=clang-7
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-7', 'clang++-7']
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: PLATFORM=Unix COMPILER=clang-7 FREETYPE=0
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-7', 'clang++-7']
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: PLATFORM=Unix COMPILER=clang-7 VALGRIND=1
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['valgrind', 'clang-7', 'clang++-7']
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
