blank_issues_enabled: true
contact_links:
  - name: Submit issues about Minetest Game
    url: https://github.com/luanti-org/minetest_game/issues/new
    about: Only submit issues of the engine in this repository's issue tracker. Submit those of Minetest Game in its own issue tracker.
  - name: Search for issue trackers of third-party games
    url: https://content.luanti.org/packages/?type=game
    about: For issues of third-party games, search for the game in the ContentDB and then submit an issue in their issue tracker.
